server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-repository: true
    service-url:
      defaultZone: http://localhost:8070/eureka/